import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconFolder,
  IconUsers,
  IconCrown,
  IconStar,
  IconBox,
  IconUserPlus,
  IconKey,
  IconShieldLock,
  IconMail,
  IconAlertCircle,
  IconLock,
  IconBan,
  IconFileOff,
  IconAlertOctagon,
  IconToolsOff,
  IconApps,
  IconMessage,
  IconHelp,
  IconChecklist,
  IconUsersGroup,
  IconComponents,
  IconList,
  IconCalendar
} from "@tabler/icons-react";

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconBox,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  workspace: IconFolder,
  teams: IconUsers,
  pro: IconCrown,
  exclusive: IconStar,
  account: IconUserCircle,
  profile: IconUser,
  signUp: IconUserPlus,
  otp: IconShieldLock,
  forgotPassword: IconKey,
  resetPassword: IconMail,
  error: IconAlertCircle,
  error401: IconLock,
  error403: IconBan,
  error404: IconFileOff,
  error500: IconAlertOctagon,
  error503: IconToolsOff,
  apps: IconApps,
  chats: IconMessage,
  helpCenter: IconHelp,
  tasks: IconChecklist,
  users: IconUsersGroup,
  components: IconComponents,
  list: IconList,
  calendar: IconCalendar
};
